using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;

namespace TensileTesterSharer
{
    public class SharedVariables
    {
        public static int AutoSpeed;
        public static double EncoderScaled;
        public static double LoadcellScaled;
        public static float LoadcellCalFac;
        public static double TestIBMpa;
        public static double TestMpa;
        public static bool CalWinTare;
        public static bool CalWinCal;
        public static double MaxForce;
        public static double ForceMpaSample1;
        public static double ForceMpaSample2;
        public static double MaxKn;
        public static double ForceKnSample1;
        public static double ForceKnSample2;
        public static double BreakForce;
        public static double EncoderRaw;
        public static double LoadcellRaw;
        public static double ReturnOffset;
        public static double AnaTest;
        public static double LoadTest;
        public static bool Servo_Rdy;
        public static bool Servo_ZSpd;
        public static bool MOETestStarted;
        public static bool TestStarted;
        public static bool TestComplete;
        public static bool Connect;
        public static string ComPort;
        public static float EncFac;
        public static int LoadFac;
        public static bool ResetChart;
        public static double Length;
        public static double Width;
        public static double Thickness;
        public static double Density;
        public static string Operator;
        public static string Foreman;
        public static string Shift;
        public static double Shf1;
        public static double Shf2;
        public static double Shf3;
        public static double Shf4;
        public static double ShfAvg;
        public static double She1;
        public static double She2;
        public static double She3;
        public static double She4;
        public static double SheAvg;
        public static double Fst1;
        public static double Fst2;
        public static double Fst3;
        public static double Fst4;
        public static double FstAvg;
        public static double Fsb1;
        public static double Fsb2;
        public static double Fsb3;
        public static double Fsb4;
        public static double FsbAvg;
        public static double IB1T;
        public static double IB2B;
        public static double IB3T;
        public static double IB4B;
        public static double IB5T;
        public static double IB6B;
        public static double IB7T;
        public static double IB8B;
        public static double IBAvg;
        public static double IB1Thick;
        public static double IB2Thick;
        public static double IB3Thick;
        public static double IB4Thick;
        public static double IB5Thick;
        public static double IB6Thick;
        public static double IB7Thick;
        public static double IB8Thick;
        public static double IBAvgThick;
        public static double IB1Read;
        public static double IB2Read;
        public static double IB3Read;
        public static double IB4Read;
        public static double IB5Read;
        public static double IB6Read;
        public static double IB7Read;
        public static double IB8Read;
        public static double IBAvgRead;
        public static double IB1Mpa;
        public static double IB2Mpa;
        public static double IB3Mpa;
        public static double IB4Mpa;
        public static double IB5Mpa;
        public static double IB6Mpa;
        public static double IB7Mpa;
        public static double IB8Mpa;
        public static double IBAvgMpa;
    }
}
